version: '3.8'

services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET} --forward-to host.docker.internal:4000/api/v1/webhook"
    env_file: ./.env
volumes: 
  db: