enum AuthErrorCode {
  NOT_LOGIN = 'NOT_LOGIN',
  FAILED_VALIDATE_BODY = 'FAILED_VALIDATE_BODY',
  SERVER_INTERNAL_ERROR = 'SERVER_INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}
export default AuthErrorCode;
